[project]
name = "django-bucket-s3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3==1.35.44",
    "django-environ>=0.11.2",
    "django==5.1.2",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.7.0",
]
